import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-background">
      <Navbar />
      <main className="container mx-auto px-4 lg:px-8 py-16">
        <article className="max-w-4xl mx-auto prose prose-invert prose-headings:text-foreground prose-p:text-foreground/80 prose-li:text-foreground/80 prose-strong:text-foreground prose-a:text-accent hover:prose-a:text-accent/80">
          <h1 className="text-4xl font-heading font-bold mb-8">Privacy Policy</h1>
          
          <h2 className="text-2xl font-heading">PRIVACY POLICY – BLINKWAY</h2>
          
          <p><strong>Effective Date:</strong> 10 August 2025</p>
          <p><strong>Last Updated:</strong> 10 August 2025</p>
          
          <hr className="border-border my-8" />
          
          <h2>1. Legal Status of This Document</h2>
          <p>
            This Privacy Policy is an <strong>electronic record</strong> in terms of the <strong>Information Technology Act, 2000</strong> and the rules made thereunder, including the amended provisions pertaining to electronic records.
          </p>
          <p>
            This electronic record is generated by a computer system and <strong>does not require any physical or digital signature</strong>.
          </p>
          <p>
            This document is published in accordance with <strong>Rule 3(1) of the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2011</strong>, which mandates publishing the Privacy Policy for access or usage of a website.
          </p>
          
          <hr className="border-border my-8" />
          
          <h2>2. Introduction</h2>
          <p>
            BLINKWAY ("Company", "we", "us", or "our") operates the website <strong><a href="https://blinkway.org">https://blinkway.org</a></strong> ("Website" or "Platform").
          </p>
          <p>
            We are committed to protecting your privacy and ensuring the security of your personal data.
          </p>
          <p>
            This Privacy Policy explains how we <strong>collect, use, store, disclose, and protect</strong> your information when you access or use our Platform or services.
          </p>
          <p>
            By using our Platform, you <strong>agree to the terms of this Privacy Policy</strong>.
          </p>
          
          <hr className="border-border my-8" />
          
          <h2>3. Information We Collect</h2>
          <p>We may collect the following categories of information:</p>
          
          <h3>a) Personal Information</h3>
          <ul>
            <li>Name</li>
            <li>Email address</li>
            <li>Phone number</li>
            <li>Billing and payment information (processed via third-party gateways)</li>
            <li>Any information voluntarily provided through forms or communication</li>
          </ul>
          
          <h3>b) Technical & Usage Information</h3>
          <ul>
            <li>IP address</li>
            <li>Browser type and version</li>
            <li>Device information</li>
            <li>Pages visited, time spent, and usage patterns</li>
            <li>Cookies and similar tracking technologies</li>
          </ul>
          
          <hr className="border-border my-8" />
          
          <h2>4. How We Use Your Information</h2>
          <p>We use collected information for the following purposes:</p>
          <ul>
            <li>To provide and deliver digital products and services</li>
            <li>To process payments and transactions</li>
            <li>To communicate with users regarding orders, updates, or support</li>
            <li>To improve our website, products, and user experience</li>
            <li>To comply with legal obligations and enforce our Terms of Service</li>
            <li>To prevent fraud, misuse, or unauthorized access</li>
          </ul>
          
          <hr className="border-border my-8" />
          
          <h2>5. Cookies & Tracking Technologies</h2>
          <p>Our Platform uses <strong>cookies and similar technologies</strong> to:</p>
          <ul>
            <li>Enhance user experience</li>
            <li>Analyze website traffic</li>
            <li>Remember user preferences</li>
          </ul>
          <p>
            You may choose to disable cookies through your browser settings; however, doing so may affect website functionality.
          </p>
          
          <hr className="border-border my-8" />
          
          <h2>6. Payment Information</h2>
          <p>
            All payments are processed through <strong>secure third-party payment gateways</strong>, including Shopify's payment partners.
          </p>
          <p>
            BLINKWAY <strong>does not store or process sensitive payment information</strong> such as credit/debit card numbers or CVV details on its servers.
          </p>
          
          <hr className="border-border my-8" />
          
          <h2>7. Disclosure of Information</h2>
          <p>We do <strong>not sell, rent, or trade</strong> your personal information.</p>
          <p>Your information may be disclosed only in the following cases:</p>
          <ul>
            <li>To trusted third-party service providers strictly for service delivery</li>
            <li>When required by law, court order, or government authority</li>
            <li>To protect our legal rights, property, or safety</li>
            <li>In connection with business transfers, mergers, or restructuring (if applicable)</li>
          </ul>
          
          <hr className="border-border my-8" />
          
          <h2>8. Data Security</h2>
          <p>
            We implement <strong>reasonable security practices and procedures</strong> as required under the <strong>Information Technology (Reasonable Security Practices and Procedures and Sensitive Personal Data or Information) Rules, 2011</strong> to protect your information from unauthorized access, misuse, or disclosure.
          </p>
          <p>
            However, no method of transmission over the internet is completely secure, and we cannot guarantee absolute security.
          </p>
          
          <hr className="border-border my-8" />
          
          <h2>9. User Rights & Choices</h2>
          <p>You have the right to:</p>
          <ul>
            <li>Access your personal information</li>
            <li>Request correction or update of your data</li>
            <li>Withdraw consent for data processing (subject to legal obligations)</li>
            <li>Request deletion of your personal information, where applicable</li>
          </ul>
          <p>Requests may be sent to our contact details provided below.</p>
          
          <hr className="border-border my-8" />
          
          <h2>10. Third-Party Links</h2>
          <p>Our Platform may contain links to third-party websites.</p>
          <p>
            We are <strong>not responsible</strong> for the privacy practices or content of such third-party websites.
          </p>
          <p>Users are encouraged to review the privacy policies of external websites separately.</p>
          
          <hr className="border-border my-8" />
          
          <h2>11. Data Retention</h2>
          <p>
            We retain personal information <strong>only for as long as necessary</strong> to fulfill the purposes outlined in this Privacy Policy, comply with legal obligations, or resolve disputes.
          </p>
          
          <hr className="border-border my-8" />
          
          <h2>12. Children's Privacy</h2>
          <p>Our services are <strong>not intended for individuals under the age of 18</strong>.</p>
          <p>
            We do not knowingly collect personal data from minors. If such data is discovered, it will be deleted promptly.
          </p>
          
          <hr className="border-border my-8" />
          
          <h2>13. Changes to This Privacy Policy</h2>
          <p>
            We reserve the right to update or modify this Privacy Policy at any time without prior notice.
          </p>
          <p>Changes will be effective immediately upon posting on the Platform.</p>
          <p>Continued use of the Platform constitutes acceptance of the updated Privacy Policy.</p>
          
          <hr className="border-border my-8" />
          
          <h2>14. Governing Law & Jurisdiction</h2>
          <p>
            This Privacy Policy shall be governed by and construed in accordance with the <strong>laws of India</strong>.
          </p>
          <p>
            Any disputes shall be subject to the <strong>exclusive jurisdiction of the courts of Roorkee, Uttarakhand, India</strong>.
          </p>
          
          <hr className="border-border my-8" />
          
          <h2>15. Contact Information</h2>
          <p>For questions, concerns, or requests related to this Privacy Policy, please contact:</p>
          <p><strong>BLINKWAY</strong></p>
          <p>Website: <a href="https://blinkway.org">https://blinkway.org</a></p>
          <p>Email: support@blinkway.org | blinkway111@gmail.com</p>
          <p>Phone: +91 9259802634</p>
        </article>
      </main>
      <Footer />
    </div>
  );
}
