import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-background">
      <Navbar />
      <main className="container mx-auto px-4 lg:px-8 py-16">
        <article className="max-w-4xl mx-auto prose prose-invert prose-headings:text-foreground prose-p:text-foreground/80 prose-li:text-foreground/80 prose-strong:text-foreground prose-a:text-accent hover:prose-a:text-accent/80">
          <h1 className="text-4xl font-heading font-bold mb-8">Terms of Service</h1>
          
          <h2 className="text-2xl font-heading">TERMS OF SERVICE – BLINKWAY</h2>
          
          <p><strong>Effective Date:</strong> 10 August 2025</p>
          <p><strong>Last Updated:</strong> 20 December 2025</p>
          
          <hr className="border-border my-8" />
          
          <h2>1. Legal Status of This Document</h2>
          <p>
            This document is an <strong>electronic record</strong> in terms of the <strong>Information Technology Act, 2000</strong> and the rules made thereunder, as applicable, and the amended provisions pertaining to electronic records in various statutes.
          </p>
          <p>
            This electronic record is generated by a computer system and <strong>does not require any physical or digital signature</strong>.
          </p>
          <p>
            This document is published in accordance with <strong>Rule 3(1) of the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2011</strong>, which requires publishing the rules and regulations, privacy policy, and terms of use for access or usage of a website.
          </p>
          
          <hr className="border-border my-8" />
          
          <h2>2. Platform Ownership</h2>
          <p>
            The website <strong><a href="https://blinkway.org">https://blinkway.org</a></strong> (hereinafter referred to as the <strong>"Website"</strong> or <strong>"Platform"</strong>) is owned and operated by <strong>BLINKWAY</strong> (hereinafter referred to as <strong>"Platform Owner"</strong>, <strong>"Company"</strong>, <strong>"we"</strong>, <strong>"us"</strong>, or <strong>"our"</strong>), having its principal place of business in <strong>Roorkee, Uttarakhand, India</strong>.
          </p>
          
          <hr className="border-border my-8" />
          
          <h2>3. Acceptance of Terms</h2>
          <p>
            Your access to, browsing of, or use of the Platform, and/or purchase of any products or services offered through the Platform, constitutes your <strong>unconditional acceptance</strong> of these Terms of Service ("Terms"), together with our Privacy Policy and Refund Policy, which are incorporated herein by reference.
          </p>
          <p>
            <strong>ACCESSING, BROWSING, OR USING THE PLATFORM INDICATES THAT YOU HAVE READ, UNDERSTOOD, AND AGREED TO BE BOUND BY THESE TERMS.</strong>
          </p>
          <p>If you do not agree with any part of these Terms, you must not use the Platform.</p>
          
          <hr className="border-border my-8" />
          
          <h2>4. Definitions</h2>
          <p>For the purposes of these Terms:</p>
          <ul>
            <li><strong>"User", "You", "Your"</strong> refers to any natural or legal person who accesses or uses the Platform.</li>
            <li><strong>"Services"</strong> include digital products, software, templates, guides, educational materials, AI tools, SaaS offerings, and related digital solutions provided by BLINKWAY.</li>
          </ul>
          
          <hr className="border-border my-8" />
          
          <h2>5. Eligibility & User Responsibility</h2>
          <p>By using this Platform, you confirm that:</p>
          <ul>
            <li>You are at least the age of majority under applicable law, or</li>
            <li>You are accessing the Platform under the supervision and consent of a legal guardian.</li>
          </ul>
          <p>
            You agree to provide <strong>true, accurate, and complete information</strong> during any registration or transaction process and are solely responsible for <strong>all activities conducted through your account</strong>, whether authorized or unauthorized.
          </p>
          
          <hr className="border-border my-8" />
          
          <h2>6. Services & Products</h2>
          <p>BLINKWAY provides <strong>digital products and services</strong> intended for business, educational, and informational purposes.</p>
          <ul>
            <li>All product descriptions, features, pricing, and availability are subject to change without prior notice.</li>
            <li>We do not guarantee that any service will meet your specific requirements or expectations.</li>
          </ul>
          
          <hr className="border-border my-8" />
          
          <h2>7. Accuracy of Information & Disclaimer</h2>
          <p>
            While we strive to keep information on the Platform accurate and up to date, <strong>we make no warranties or guarantees</strong> regarding the accuracy, completeness, reliability, suitability, or availability of any information, products, or services.
          </p>
          <p>You acknowledge that:</p>
          <ul>
            <li>The Platform content may contain errors or inaccuracies.</li>
            <li>Your use of the Platform and Services is <strong>entirely at your own risk and discretion</strong>.</li>
          </ul>
          
          <hr className="border-border my-8" />
          
          <h2>8. Pricing & Payments</h2>
          <ul>
            <li>Prices may be displayed in <strong>USD and/or INR</strong> and are subject to change without notice.</li>
            <li>Full payment is required before delivery or access to any digital product or service.</li>
            <li>Payments are processed through <strong>Shopify's secure payment gateways</strong> and/or authorized third-party payment processors.</li>
          </ul>
          <p>We are not responsible for payment gateway errors, bank delays, or third-party payment failures.</p>
          
          <hr className="border-border my-8" />
          
          <h2>9. Refund Policy</h2>
          <p>Due to the <strong>digital nature</strong> of our products and services:</p>
          <ul>
            <li><strong>All sales are final</strong></li>
            <li><strong>No refunds, cancellations, or exchanges</strong> are permitted once a product is delivered, downloaded, or accessed.</li>
          </ul>
          <p>Users are advised to review product details carefully before making a purchase.</p>
          
          <hr className="border-border my-8" />
          
          <h2>10. Intellectual Property Rights</h2>
          <p>
            All content on the Platform, including but not limited to text, graphics, logos, designs, software, digital products, and downloadable materials, are the <strong>exclusive intellectual property of BLINKWAY</strong> or its licensors.
          </p>
          <p>You shall not:</p>
          <ul>
            <li>Copy, reproduce, distribute, modify, resell, or exploit any content</li>
            <li>Use our intellectual property without <strong>prior written consent</strong></li>
          </ul>
          <p>Unauthorized use may result in <strong>legal action under applicable laws</strong>.</p>
          
          <hr className="border-border my-8" />
          
          <h2>11. Prohibited Uses</h2>
          <p>You agree not to use the Platform or Services for:</p>
          <ul>
            <li>Any unlawful or illegal purpose</li>
            <li>Violating intellectual property or proprietary rights</li>
            <li>Transmitting malware, viruses, or harmful code</li>
            <li>Collecting personal data without consent</li>
            <li>Any activity that disrupts or damages the Platform</li>
          </ul>
          
          <hr className="border-border my-8" />
          
          <h2>12. Third-Party Links</h2>
          <p>The Platform may contain links to third-party websites or services.</p>
          <p>
            BLINKWAY has <strong>no control over and assumes no responsibility</strong> for the content, policies, or practices of such third parties.
          </p>
          <p>Accessing third-party websites is at your own risk.</p>
          
          <hr className="border-border my-8" />
          
          <h2>13. Indemnification</h2>
          <p>
            You agree to <strong>indemnify, defend, and hold harmless</strong> BLINKWAY, its affiliates, officers, employees, and agents from any claims, damages, losses, liabilities, costs, or expenses (including reasonable attorney fees) arising from:
          </p>
          <ul>
            <li>Your breach of these Terms</li>
            <li>Your misuse of the Platform or Services</li>
            <li>Violation of any law or third-party rights</li>
          </ul>
          
          <hr className="border-border my-8" />
          
          <h2>14. Limitation of Liability</h2>
          <p>To the maximum extent permitted by law:</p>
          <ul>
            <li>BLINKWAY shall <strong>not be liable</strong> for any indirect, incidental, consequential, special, or punitive damages, including loss of profits, data, or business opportunities.</li>
            <li>Our total liability, if any, shall <strong>not exceed the amount paid by you for the specific service giving rise to the claim or INR 100 (Rupees One Hundred), whichever is lower</strong>.</li>
          </ul>
          
          <hr className="border-border my-8" />
          
          <h2>15. Force Majeure</h2>
          <p>
            BLINKWAY shall not be liable for failure or delay in performance due to events beyond reasonable control, including but not limited to acts of God, natural disasters, war, strikes, government actions, internet outages, or technical failures.
          </p>
          
          <hr className="border-border my-8" />
          
          <h2>16. Termination</h2>
          <p>
            We reserve the right to suspend or terminate your access to the Platform or Services at any time, without prior notice, if you violate these Terms or applicable laws.
          </p>
          
          <hr className="border-border my-8" />
          
          <h2>17. Modifications to Terms</h2>
          <p>We may update or modify these Terms at any time without prior notice.</p>
          <p>Continued use of the Platform after changes are posted constitutes acceptance of the revised Terms.</p>
          
          <hr className="border-border my-8" />
          
          <h2>18. Governing Law & Jurisdiction</h2>
          <p>
            These Terms shall be governed by and construed in accordance with the <strong>laws of India</strong>.
          </p>
          <p>
            All disputes shall be subject to the <strong>exclusive jurisdiction of the courts of Roorkee, Uttarakhand, India</strong>.
          </p>
          
          <hr className="border-border my-8" />
          
          <h2>19. Contact Information</h2>
          <p>For any questions, concerns, or legal communications regarding these Terms, please contact:</p>
          <p><strong>BLINKWAY</strong></p>
          <p>Website: <a href="https://blinkway.org">https://blinkway.org</a></p>
          <p>Email: support@blinkway.org | blinkway111@gmail.com</p>
          <p>Phone: +91 9259802634</p>
        </article>
      </main>
      <Footer />
    </div>
  );
}
